Bugfix/#69 fix action pipeline deadlocks and other issues that cause random action cancelations.
openbase/bco pull request #89
Opened 2022-12-11 16:38 UTC by DivineThreepwood

### :scroll: Description

Changes proposed in this pull request:
* fix potential deadlock between actionDescriptionBuilderLock and actionTaskLock in ActionImpl.
* make sure reschedule is not triggered once the unit controller is shutting down to avoid lots of exceptions.
* Make sure required state observer is shutdown in case the scene state changes to not interfere with future scene activations. Improve required state validation by filtering by validate the initial action to avoid scene cancelation based on an outdated action. Minor typo fixes.
* fix logic issue in equalServiceStates check.
* Implement validateInitialAction service method for Actions.
* Make sure remote action cleanup task does not cleanup the state of other actions that are later observed by the same remote instance, by canceling the cleanup task once the remote is reinitialized.
* make sure remote action list is always locked once accessed.
* Code readability improvements.
* clearly define start and end of an bco test to enable the separation of test prints vs. setup / cleanup prints.
* improve test logging.

2022-12-13 11:04 UTC, pLeminoq requested changes
Overall, a really nice PR. I just have suggestions for a few minor changes and I think the actionTask issue has to be discussed.

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/action/ActionImpl.java
> +    // otherwise deadlocks can occur.
This comment is not entirely clear to me, especially with regard to the proposed change below. There are two possibilities:
1. We always need to acquire the data lock if we need the the action task lock and the data lock has to be acquired first.
2. We don't need to acquire the data lock in every case we need the action task look. But if we do, the data lock has to be acquired first.

I think you mean option 2. But in light of the proposed change below, this is not easily visible since the requirement to acquire the data lock is hidden in the `isTerminating()` call.

In general, I think the usage of such a comment is sub-optimal as you will not see this comment during coding. Would it be possible to implement a structure where when you acquire the action task lock, you have to consciously decide if you also need to acquire the data lock?

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +                                ExceptionPrinter.printHistory("Required " + requiredAction + " of " + getLabel("?") + " could not executed!", ex, logger, LogLevel.DEBUG);
```suggestion
                                ExceptionPrinter.printHistory("Required " + requiredAction + " of " + getLabel("?") + " could not be executed!", ex, logger, LogLevel.DEBUG);
```

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +                                ExceptionPrinter.printHistory("Optional " + optionalAction + " of " + getLabel("?") + " could not executed!", ex, logger, LogLevel.TRACE);
```suggestion
                                ExceptionPrinter.printHistory("Optional " + optionalAction + " of " + getLabel("?") + " could not be executed!", ex, logger, LogLevel.TRACE);
```

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
>                          // observer will cleanup itself after the action is no longer valid so no need to care fore it.
I guess the second line of this comment is now outdated and should be removed.

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +                // logger.trace("verify "+unitAndRequiredServiceStateMap.entrySet().size()+ " states of "+ getLabel("?"));
Maybe remove commented debug log

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +                throw new VerificationFailedException("The activation of "+getLabel("?") + " is not valid anymore.");
This line is not properly formatted. Maybe re-run automatic formatting on this file.

```suggestion
                throw new VerificationFailedException("The activation of " + getLabel("?") + " is not valid anymore.");
```

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +            // skip in case to service state was delivered
```suggestion
            // skip in case no service state was delivered
```

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +                // LOGGER.warn(unitAndRequiredServiceStateMap.get(unit).getServiceState() + " is not equals " + serviceState.toString().substring(0, 20) + " and will cancel: " + SceneControllerImpl.t
Maybe remove commented log

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java
> +                // logger.error("Incomming service state update from "+ serviceStateProvider.getServiceProvider().getId() + " triggered from "+ serviceState.toString());
Maybe remove commented log

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/Actions.java
> +            // skip validation is error case.
```suggestion
            // skip validation in error case.
```

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/RemoteAction.java
> +                // we do not need to cancel a running actions because its rejected on the target unit anyway when the new action is executed.
```suggestion
                // we do not need to cancel a running action because it is rejected on the target unit anyway when the new action is executed.
```

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/RemoteAction.java
> +            description = ActionDescriptionProcessor.toString(actionParameter);
Since the `description` is set to an empty string above you `description.isEmpty()` should be used instead of the null checks.

2022-12-13 11:04 UTC, pLeminoq commented on module/dal/test/src/test/java/org/openbase/bco/dal/test/layer/unit/scene/SceneRemoteTest.java
> +            LOGGER.warn("turn off... continue");
Are these debugging logs still required?

2022-12-13 23:08 UTC, DivineThreepwood commented
Thanks for the detailed review. All conversations are addressed, so PR is ready to review again.

2022-12-14 12:24 UTC, pLeminoq approved these changes

2022-12-14 22:24 UTC, merged